apiVersion: apps/v1

kind: Deployment

metadata:
  name: busybox

spec:
  selector:
    matchLabels:
      app: app-busybox
  template:
    metadata:
      labels:
        app: app-busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.31.0
        command:
          - sleep
          - "3600"
          