apiVersion: apps/v1

kind: Deployment

metadata:
  name: haproxy

spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.4-dev-alpine
        ports:
        - containerPort: 80
