apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx
  

spec:
  replicas: 3

  selector:
    matchLabels:
      app: proxy
      webserver: nginx 
      
  template:
    metadata:
      labels:
        app: proxy
        webserver: nginx 
        
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80